#!/usr/bin/env node
/*
 * Poor man's API Extractor. Walks each entry point's public-api.ts, resolves the re-exported
 * files and writes the exported symbol list to docs/api/<entry>.api.md. Consumers diff these
 * between versions; the PR check (`api:check`) fails when a report changed without a CHANGELOG
 * entry under [Unreleased].
 *
 * We tried @microsoft/api-extractor in 2021 (CNPY-1188) and gave up on the .d.ts rollup for
 * secondary entry points. This is 150 lines and has not needed touching since.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const libRoot = path.join(root, 'projects', 'canopy-ui');
const docsDir = path.join(root, 'docs', 'api');
const check = process.argv.includes('--check');

const entries = [{ name: 'canopy-ui', file: path.join(libRoot, 'src', 'public-api.ts') }];
for (const dir of fs.readdirSync(path.join(libRoot, 'src', 'lib'), { withFileTypes: true })) {
  const api = path.join(libRoot, 'src', 'lib', dir.name, 'public-api.ts');
  if (dir.isDirectory() && fs.existsSync(api)) {
    entries.push({ name: `canopy-ui/${dir.name}`, file: api });
  }
}

const EXPORT_RE = /^export\s+(?:declare\s+)?(?:abstract\s+)?(class|interface|type|const|function|enum|let)\s+([A-Za-z0-9_$]+)/gm;
const REEXPORT_RE = /^export\s+\*\s+from\s+'([^']+)';/gm;
const NAMED_REEXPORT_RE = /^export\s+\{([^}]+)\}\s+from\s+'([^']+)';/gm;

function resolve(from, spec) {
  const base = path.resolve(path.dirname(from), spec);
  for (const c of [base + '.ts', path.join(base, 'index.ts'), path.join(base, 'public-api.ts')]) {
    if (fs.existsSync(c)) return c;
  }
  return null;
}

function collect(file, seen = new Set(), out = []) {
  if (!file || seen.has(file)) return out;
  seen.add(file);
  const text = fs.readFileSync(file, 'utf8');
  let m;
  while ((m = EXPORT_RE.exec(text))) {
    out.push({ kind: m[1], name: m[2], file: path.relative(libRoot, file).replace(/\\/g, '/') });
  }
  while ((m = NAMED_REEXPORT_RE.exec(text))) {
    const target = resolve(file, m[2]);
    const names = m[1].split(',').map(s => s.trim().split(/\s+as\s+/).pop()).filter(Boolean);
    const inner = collect(target, new Set(seen), []);
    for (const n of names) {
      const hit = inner.find(i => i.name === n);
      out.push(hit || { kind: 'unknown', name: n, file: path.relative(libRoot, target || file).replace(/\\/g, '/') });
    }
  }
  while ((m = REEXPORT_RE.exec(text))) {
    collect(resolve(file, m[1]), seen, out);
  }
  return out;
}

function render(entry, symbols) {
  const lines = [`# API report: @meridian/${entry.name}`, '', 'Generated by scripts/api-report.js. Do not edit by hand.', ''];
  const byKind = {};
  for (const s of symbols) (byKind[s.kind] = byKind[s.kind] || []).push(s);
  for (const kind of Object.keys(byKind).sort()) {
    lines.push(`## ${kind}`, '');
    const uniq = new Map();
    for (const s of byKind[kind]) uniq.set(s.name, s);
    for (const s of [...uniq.values()].sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- \`${s.name}\` (${s.file})`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

fs.mkdirSync(docsDir, { recursive: true });
let changed = 0;
for (const entry of entries) {
  const report = render(entry, collect(entry.file));
  const target = path.join(docsDir, `${entry.name.replace('/', '.')}.api.md`);
  const previous = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
  if (previous !== report) {
    changed++;
    if (check) {
      console.error(`API report out of date: ${path.relative(root, target)}`);
    } else {
      fs.writeFileSync(target, report);
      console.log(`wrote ${path.relative(root, target)}`);
    }
  }
}

if (check && changed) {
  console.error(`${changed} report(s) changed. Run \`npm run api:report\` and add a CHANGELOG entry.`);
  process.exit(1);
}
if (!changed) console.log('API reports up to date');
